### ISSUE TITLE
Options in `.JuliaFormatter.toml` are ignored.

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-julia#340]
I have placed the following `.JuliaFormatter.toml` file on my repo root, but the options seem not taken into account when I'm invoking *e.g.* `<Plug>(coc-format)`:
```toml
whitespace_in_kwargs = false
indent = 1 # (just to make it obvious if it's working)
```
What could be wrong? Where is the formatter run from?
